# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0003_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glass',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='location',
            field=models.CharField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
