# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0004_auto_20170826_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='location',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(default='', max_length=254),
        ),
    ]
