# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0005_auto_20170826_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beer',
            new_name='BeerModel',
        ),
    ]
