# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='beer_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
