# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0010_auto_20170828_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beermodel',
            options={'verbose_name': 'Beer Name', 'verbose_name_plural': 'Beer Names'},
        ),
    ]
