# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0012_auto_20170828_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beermodel',
            name='abv',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='beermodel',
            name='calories',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='beermodel',
            name='ibu',
            field=models.IntegerField(default=''),
        ),
    ]
