# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beer_tracker', '0015_auto_20170828_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
