# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0017_auto_20170830_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='appearance',
            field=models.PositiveIntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratemodel',
            name='aroma',
            field=models.PositiveIntegerField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratemodel',
            name='taste',
            field=models.PositiveIntegerField(choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='10', max_length=2),
        ),
    ]
