# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beer_tracker', '0020_auto_20170830_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
